# Generated by Django 3.2.9 on 2021-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.TextField(max_length=255),
        ),
    ]
