# Generated by Django 3.2.9 on 2021-11-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='webpage',
            field=models.TextField(default='', max_length=99),
        ),
    ]
